/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.12.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package task7.server.api;

import task7.server.model.PayResponse;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import org.springframework.http.codec.multipart.Part;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-08-11T20:31:47.539634100+05:00[Asia/Yekaterinburg]", comments = "Generator version: 7.12.0")
@Validated
@Tag(name = "pay", description = "the pay API")
public interface PayApi {

    /**
     * PATCH /api/pay : Оплата заказа
     *
     * @param price цена покупки (required)
     * @return Заказ оформлен (status code 200)
     *         or Недостаточно средств для покупки (status code 400)
     *         or Внутренняя ошибка сервера (status code 500)
     */
    @Operation(
        operationId = "payOrder",
        summary = "Оплата заказа",
        tags = { "pay" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Заказ оформлен", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PayResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Недостаточно средств для покупки", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PayResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PayResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = "/api/pay",
        produces = { "application/json" }
    )
    
    Mono<ResponseEntity<PayResponse>> payOrder(
        @NotNull @Parameter(name = "price", description = "цена покупки", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "price", required = true) Long price,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );

}
