spring:
  application:
    name: MyOnlineStoreReactive
  r2dbc:
    url: r2dbc:h2:mem:///~/db/testdb;DB_CLOSE_DELAY=-1 #MODE=MYSQL # URL подключения к БД
    username: sa
    password:
  h2:
    console:
      enabled: true
logging:
  level:
    io:
      r2dbc:
        h2: TRACE
        QUERY: DEBUG # for queries
        PARAM: DEBUG # for parameters